# Generated by Django 6.1.1 on 2026-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='grade',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(),
        ),
    ]
