# Generated by Django 6.1.1 on 2026-10-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_name',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
