# Generated by Django 6.1.1 on 2026-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_created_at_remove_subject_description'),
        ('teachers', '0004_rename_first_name_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='subjects.subject'),
        ),
    ]
